# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'INTERFACE.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QFileDialog, QVBoxLayout, QTableWidget, \
    QStackedWidget, QMessageBox, QWidget, QProgressBar, QComboBox
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 888)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("background-color: rgb(40, 40, 42);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 750, 241, 61))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 24pt \"Roboto\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_file_dialog)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 750, 241, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 24pt \"Roboto\";")
        self.pushButton_2.setObjectName("pushButton_2")

        # TABLE BUILDING
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 50, 1141, 595))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setColumnWidth(0, 582)
        self.tableWidget.setColumnWidth(1, 107)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.setColumnWidth(3, 150)
        self.tableWidget.setColumnWidth(4, 150)

        # Supprimer la numérotation des lignes
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setVisible(False)
        # Rendre toutes les cellules non sélectionnables après avoir configuré la table
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        # Générer les 14 premières lignes vides
        for i in range(0, 16):
            self.tableWidget.insertRow(i)

        # Définir la couleur de fond pour les cellules "Nom du fichier", "format", "Taille", "Statut", "Temps restant"
        cell_background_color = QtGui.QBrush(QtGui.QColor("#bcdcf4"))

        # Colonne 0 : "Nom du fichier"
        self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem("Nom du fichier"))
        self.tableWidget.item(0, 0).setBackground(cell_background_color)
        self.tableWidget.item(0, 0).setTextAlignment(QtCore.Qt.AlignCenter)

        # Colonne 1 : "format"
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem("format"))
        self.tableWidget.item(0, 1).setBackground(cell_background_color)
        self.tableWidget.item(0, 1).setTextAlignment(QtCore.Qt.AlignCenter)

        # Colonne 2 : "Taille"
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem("Taille"))
        self.tableWidget.item(0, 2).setBackground(cell_background_color)
        self.tableWidget.item(0, 2).setTextAlignment(QtCore.Qt.AlignCenter)

        # Colonne 3 : "Statut"
        self.tableWidget.setItem(0, 3, QtWidgets.QTableWidgetItem("Statut"))
        self.tableWidget.item(0, 3).setBackground(cell_background_color)
        self.tableWidget.item(0, 3).setTextAlignment(QtCore.Qt.AlignCenter)

        # Colonne 4 : "Temps restant"
        self.tableWidget.setItem(0, 4, QtWidgets.QTableWidgetItem("Temps restant"))
        self.tableWidget.item(0, 4).setBackground(cell_background_color)
        self.tableWidget.item(0, 4).setTextAlignment(QtCore.Qt.AlignCenter)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open_file_dialog(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.ReadOnly

        file_dialog = QtWidgets.QFileDialog()
        video_files, _ = file_dialog.getOpenFileNames(None, "Sélectionner des fichiers média", "",
                                                      "Fichiers Média (*.mp4 *.avi *.mkv *.mp3 *.wav *.mov);;Tous les fichiers (*)",
                                                      options=options)

        if video_files:
            self.selected_files = video_files

            # Ajoutez une nouvelle ligne pour chaque fichier sélectionné
            #for i, file_path in enumerate(self.selected_files):

            # Recherche de la première ligne vide (i + 1 car la première ligne est déjà occupée)
            current_row = 1
            while self.tableWidget.item(current_row, 0) is not None:
                current_row += 1

            for file_path in self.selected_files:
                if current_row >= self.tableWidget.rowCount():
                    # Vous pouvez ajouter du code ici pour gérer la situation si toutes les lignes sont déjà occupées.
                    self.tableWidget.insertRow(current_row)
                    # Par exemple, afficher un message d'erreur ou augmenter la taille de la table.
                    # Pour l'instant, nous supposons que vous gérez le cas où toutes les lignes sont occupées.

                file_name = os.path.basename(file_path)

                # Colonne 1 : Noms des fichiers
                item = QtWidgets.QTableWidgetItem(file_name)
                # item.setFlags(item.flags() & ~QtCore.Qt.ItemIsSelectable(False))
                self.tableWidget.setItem(current_row, 0, item)

                # Colonne 2 : Format de fichier à convertir
                # Créez une liste de formats multimédias
                multimedia_formats = ["*.mp4", "*.avi", "*.mkv", "*.mp3", "*.wav", "*.mov"]
                # Ajoutez d'autres formats si nécessaire
                # Créez un QComboBox et ajoutez les formats multimédias à l'intérieur
                format_combobox = QtWidgets.QComboBox()
                format_combobox.addItems(multimedia_formats)
                # Insérez le QComboBox dans la cellule de la deuxième ligne de la colonne "format"
                self.tableWidget.setCellWidget(current_row, 1, format_combobox)

                # Colonne : Taille des fichiers
                file_size = os.path.getsize(file_path)
                item = QtWidgets.QTableWidgetItem(str(file_size))
                # Convertir la taille en méga-octets (Mo) ou giga-octets (Go)
                if file_size >= 1024 ** 3:  # Si la taille est supérieure ou égale à 1 Go
                    size_str = f"{file_size / (1024 ** 3):.2f} Go"
                else:  # Sinon, convertir en Mo
                    size_str = f"{file_size / (1024 ** 2):.2f} Mo"
                item = QtWidgets.QTableWidgetItem(size_str)
                # item.setFlags(item.flags() & ~QtCore.Qt.ItemIsSelectable(False))
                self.tableWidget.setItem(current_row, 2, item)
                self.tableWidget.item(current_row, 2).setTextAlignment(QtCore.Qt.AlignCenter)

                current_row += 1  # Passe à la prochaine ligne libre pour le prochain fichier

            print("Vidéos sélectionnées :", self.selected_files)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "selectionner"))
        self.pushButton_2.setText(_translate("MainWindow", "convertir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
